### ISSUE TITLE
内核solon模块精简讨论

### ISSUE THREAD

**Issue by sppan24** [opensolon/solon#240]
solon模块作为整个项目的内核，从我目前比较粗浅的理解来看，可以进行一定的精简，使得项目层次更加容易理解。大概调整逻辑为：
将mvc、router、handle等功能从模块中剥离，solon模块只保留项目配置初始化，生命周期管理，事件传播等功能。

**Comment by noear** [comment]
之前也有很多人这么提过。从技术角度，分开确实更好。从实用角度，真不好说！

**Comment by sppan24** [comment]
> 这里有两个方面：
> 
> 1. 从实用角度，现在应该是更好的，而且确实也不大。。。从技术角度，分开更好，显得内核更内核，且结构更清晰。
> 2. 历史原因，需要向上兼容。。。2.7.0 时 mvc 已经独立出去了，在发包那一刻又合回来了（就是怕造成兼容问题）

理想和现实确实总是有差距的，这个不可避免。。
