### ISSUE TITLE
建议官网RPC未来支持高性能序列化框架-flatbuffers和simple-binary-encoding

### ISSUE THREAD

**Issue by cnrainbing** [opensolon/solon#257]
1. 他们两个的易用性也是非常高的
2. https://github.com/real-logic/simple-binary-encoding
3. https://github.com/google/flatbuffers

**Comment by noear** [comment]
https://github.com/real-logic/simple-binary-encoding

这个项目里，没有 java 的实现！

**Comment by cnrainbing** [comment]
> https://github.com/real-logic/simple-binary-encoding
> 
> 这个项目里，没有 java 的实现！

希望支持 nami-coder-sbe 编解码，我没看懂simple-binary-encoding如何使用

**Comment by noear** [comment]
@cnrainbing 它没 java 的 sdk；怎么加呢？

**Comment by cnrainbing** [comment]
> @cnrainbing 它没 java 的 sdk；怎么加呢？

https://mvnrepository.com/artifact/uk.co.real-logic/sbe-all


<dependency>
    <groupId>uk.co.real-logic</groupId>
    <artifactId>sbe-all</artifactId>
    <version>1.33.1</version>
</dependency>

**Comment by noear** [comment]
真晕。看错了。。。后续会研究

**Comment by cnrainbing** [comment]
> 真晕。看错了。。。后续会研究

非常感谢

**Comment by noear** [comment]
solon-serialization-sbe 模块，更名成了 solon-serialization-abc （扩展更自由的方式）//后面仍可能会改名字

你可以在里面，再接着加 chronicle-bytes , flatbuffers 之类的实现（参考 sbe 的子目录）

**Comment by cnrainbing** [comment]
chronicle-bytes 基本结束，我开始研究一下 flatbuffers 只在java 之间调用，不写IDL 描述文件是否可以使用

**Comment by noear** [comment]
3.0.4 已发布
