### ISSUE TITLE
IOC包扫描时排队某些包

### ISSUE THREAD

**Issue by juqkai** [opensolon/solon#268]
我的程序包结构中，有一个子包，我需要在后面才把它加载起来，在启动的时候不需要加载。所以需要在solon启动的时候将其排除掉。等需要的时候再对这个包进行扫描与加载。

**Comment by noear** [comment]
有一个方案是：把这个子包，移到扫描不到的地方

**Comment by noear** [comment]
不知道 spring 是怎么做的，我参考下：）

**Comment by noear** [comment]
有个好方案了（一个用户用的），不要加注解。。。需要时，通过 Solon.context().getBeanOrNew(clz); 获取
