### ISSUE TITLE
后扫描的包，依赖注入List对象为空

### ISSUE THREAD

**Issue by juqkai** [opensolon/solon#272]
我有一个包，Solon启动的时候并未添加到扫描路径下。启动成功后，因某些原因需要将这个包纳入ioc进行管理，使用了如下的语句进行操作：
```
Solon.context().beanScan(Test.class);

其中
class Test{
@Inject
List<Abc> abc;
}
```

操作后，类可以获取到，但是内里面的abc属性为空。只能手动再调用一次获取
Solon.context().getBeansOfType(Abc.class);

**Comment by noear** [comment]
启动完成后，就不会再执行注入了。。。只能通过接口获取
