### ISSUE TITLE
安卓中运行solon，发现bug

### ISSUE THREAD

**Issue by dmwhw** [opensolon/solon#276]
发现了这个代码中，为什么先使用，后判空？有点抽象了。
这个bug是我在安卓内运行发现的

![image](https://github.com/opensolon/solon/assets/14970718/faad4588-0acd-45fc-b928-69ebd4fd16ed)

![image](https://github.com/opensolon/solon/assets/14970718/d15bbdab-0cac-4dc4-8a31-616810e33598)

**Comment by noear** [comment]
你把 solon 运行在 安卓里。。。估计不行。。。它定位是搞后端的

**Comment by noear** [comment]
且是基于完整的 java jre 运行的。。。android 应该是有些限制的。

**Comment by dmwhw** [comment]
我这边要搞个嵌入式开发。它依赖比较小，然后尝试把它放里面。jr依赖的我尝试去处理了

**Comment by dmwhw** [comment]
能不能 处理下它上面的抽象判空
![image](https://github.com/opensolon/solon/assets/14970718/92e98fc3-11be-43b4-bc3d-ac239039fd6a)

**Comment by dmwhw** [comment]
我试试找下其他办法。

**Comment by noear** [comment]
你拉取 solon 的源码，尝试在本地修改，然后本地 install。。。如果能调通，把代码同步到主参仓库
