### ISSUE TITLE
lettuce-solon-plugin native编译出来的包,无法注入配置

### ISSUE THREAD

**Issue by arvinzhen** [opensolon/solon#277]
![image](https://github.com/opensolon/solon/assets/30438851/2accc0aa-7121-4495-ada3-8a50717fcdc0)

**Comment by noear** [comment]
native编译。。。比较麻烦。。。这种情况，你可以添加些手动的注册（具体要研究）

**Comment by arvinzhen** [comment]
有啥方向嘛 无处下手🥲

西东 ***@***.***> 于2024年6月22日周六 11:30写道：

**Comment by noear** [comment]
细节我也不好讲。。。官网的原生编译相关的材料，一定要熟

**Comment by arvinzhen** [comment]
你好呀, 似乎是注入配置的问题[image: image.png]
改成先注入配置就行了, ***@***.***("${cache.redis1}")

西东 ***@***.***> 于2024年6月27日周四 16:05写道：
