### ISSUE TITLE
自定义的注解校验器如何实现与内置校验一样的分组校验功能？

### ISSUE THREAD

**Issue by blackknifes** [opensolon/solon#291]
内置校验器注解都带有groups属性，
官方示例自定义校验器没有加上groups属性并且也没有实现分组校验功能，如果要实现自定义校验器的分组校验，如何去做？

**Comment by noear** [comment]
我调整了官网的资料：
https://solon.noear.org/article/49
看下：3、尝试添一个扩展校验注解
