### ISSUE TITLE
事务问题

### ISSUE THREAD

**Issue by akssmaw** [opensolon/solon#293]
我想用try catch抛出报错原因 
![image](https://github.com/user-attachments/assets/64fd2d8f-1e16-4eb5-a589-2c22b9383942)
用了这样的写法 catch正常抛出 事务无法回滚
去掉try catch 事务正常回滚 
需要增加什么注解吗

**Comment by noear** [comment]
事务回滚，是由异常触发的。。。如果，你吃掉了。就触发不了了。

**Comment by akssmaw** [comment]
那我现在如何使事务正常回滚 并返回error信息

**Comment by akssmaw** [comment]
> 事务回滚，是由异常触发的。。。如果，你吃掉了。就触发不了了。


那我现在如何使事务正常回滚 并返回error信息

**Comment by noear** [comment]
你可以定制一个异常。。。里面，可以放 R 实例的。。。然后，在全局异常处理时，获取 R

**Comment by noear** [comment]
或者你试一下，内核提供的一个异常：

```java
thow new DataThrowable(e).data(R.error("xxxx")); //替代 return R.error("xxxx")
```

//这个异常在 Action 里，会自动读取 data 并渲染的

**Comment by akssmaw** [comment]
> 或者你试一下，内核提供的一个异常：
> 
> ```java
> throw new DataThrowable(e).data(R.error("xxxx")); //替代 return R.error("xxxx")
> ```
> 
> //这个异常在 Action 里，会自动读取 data 并渲染的

感恩 完美解决 谢谢老哥
