### ISSUE TITLE
关于@Cache 注解在 @Component 注解类下使用咨询

### ISSUE THREAD

**Issue by TreasureLand** [opensolon/solon#296]
如下， @Component 注解类下使用咨询，MyService 中的 方法1 调用  方法2，方法2有注解 @Cache，实际上，在方法1调用 方法2 时候，注解没有生效，请问是设计如此的吗？

```java
@Controller
public class MyController {
    @Inject
    private MyService myService;
  @Mapping("/路由1")
    @Post
    public Ret 路由方法1 () {
        return myService.方法1()
    }

}
```

```java
@Component 
public class MyService {

@Cache(key="方法1",second="100)
方法2 {
  return "缓存";
}

方法1 {
  return 方法2();
}


}
```

**Comment by noear** [comment]
@Cache 及其它 Aop 的注解使用。会涉及一个动态代理的知识：

动态代理后，类实际会有两层：外层为代理类（处理Aop注解）；内层为真实类。。。。

平常调用是：使用者->(代理类->真实类)，此时Aop的注解会生效。。。

如果在真实类里，this 调用自己，就会是：真实类-》真实类。。。跳过了代理类。。。所以会失效。

---

所有的类代理，都差不多。。。如果想自己调用自己，仍估 AOP 有效。。。要使用：自己注入自己

```java
@Component 
public class MyService {
    @Inject
    MyService self;
}
```

使用注入的自己，来调用有 aop 需求的方法。

**Comment by noear** [comment]
官网有详解：

https://solon.noear.org/article/442
