### ISSUE TITLE
[咨询] solon的IOC容器是通过反射实现的吗？

### ISSUE THREAD

**Issue by xflcx1991** [opensolon/solon#298]
在学习中，请问solon的IOC容器是类似Spring那样的反射实现的吗？

我看到“手写Srping”中，号称是模拟Spring方式，我大概看懂了，这个教程就是简单粗暴的递归扫描包路径然后递归查询注解，保存beanDefinetion信息，最后在new一个对象。充斥着递归扫描和反射。

https://liaoxuefeng.com/books/summerframework/introduction/index.html

我另外搜到Spring 5开始有了@Index 方式可以通过APT在编译期就搞定注解的信息，不用再递归扫描了。

到此好奇solon的IOC容器实现机制是怎么样的。

我在考虑如果另外一个语言有宏有AST解析树，是不是可以彻底在编译期搞定IOC的注册问题。

**Comment by noear** [comment]
IOC 可以分为两种，自动 与 手动。

自动的，需要借助 java 反射。。。这个事与 spring 无关，且 ioc 的容器也有别的。大家都基于 java 反射。扫描包，也是常见的方式。（solon 就是这种方式）

手动的，这里可以了解下：https://solon.noear.org/article/543

自动，是在手动的基础上，加了些自动的事：自动搜集，自动赋值。

**Comment by xflcx1991** [comment]
> IOC 可以分为两种，自动 与 手动。
> 
> 自动的，需要借助 java 反射。。。这个事与 spring 无关，且 ioc 的容器也有别的。大家都基于 java 反射。扫描包，也是常见的方式。（solon 就是这种方式）
> 
> 手动的，这里可以了解下：https://solon.noear.org/article/543
> 
> 自动，是在手动的基础上，加了些自动的事：自动搜集，自动赋值。

谢谢。
