### ISSUE TITLE
Should we add solon to TechEmpower benchmarks?

### ISSUE THREAD

**Issue by pmg1991** [opensolon/solon#80]

**Comment by noear** [comment]
我觉得可以加：）。。。不过，我英文不好，不是中文的网站都不大熟。

**Comment by noear** [comment]
帮忙多介绍些用户。希望今年，能让 star 加到 1000 个：）

**Comment by pmg1991** [comment]
Create one benchmark comparing Quarkus, Micronaut, Spring , Helidon and Solon, Both performance and deployment size. Then share link to Hacker News. You'll get the expected exposure .

**Comment by noear** [comment]
https://github.com/noear/helloworld_wrk_test

我之前建过这个测试项目。你看看怎么样？

**Comment by noear** [comment]
你可以帮忙。。。加上 Quarkus, Micronaut, Helidon 的测试代码吗？

**Comment by pmg1991** [comment]
> 你可以帮忙。。。加上 Quarkus, Micronaut, Helidon 的测试代码吗？

Yes I will

**Comment by noear** [comment]
朋友。。。Solon 2.0 发布了，帮忙宣传一下：）

**Comment by pmg1991** [comment]
I've crated the initial code here https://github.com/pmg1991/FrameworkBenchmarks/tree/master/frameworks/Java/solon

Can you check it, If every thing looks ok I will push this to original Techem benchmark. 

Also can you help to setup orm for postgres?

**Comment by noear** [comment]
非常感觉，我晚上去测试一下：）

**Comment by noear** [comment]
正常运行没问题，但用 wrk 测的时候好像有问题。。。我明天再好好研究一下

**Comment by pmg1991** [comment]
When compared to [smart-http](https://github.com/pmg1991/FrameworkBenchmarks/tree/master/frameworks/Java/smart-socket) ,  Solon seems a little slower ( 16K  vs 14K request per sec on my machine)  Can you check if it can be optimized?

One place I found is https://github.com/noear/solon/blob/6e0f6f8f9591ec3408c2edfcde5291835adb1ed8/_solon_boot/solon.boot.smarthttp/src/main/java/org/noear/solon/boot/smarthttp/http/SmartHttpContextHandler.java#L51  , a new  SmartHttpContext is created for every request can this be pooled?

**Comment by noear** [comment]
添加应用配置：“server.http.ioBound=false”。程序在 cpu 密集型 和 io 密集型下，线程配置不同。。。要跑分高，需要加：“server.http.ioBound=false”。。。。我已经在你的代码仓库上，提交了 pr。。。你再看一下

**Comment by pmg1991** [comment]
It was faster :) , Raised Pull to Upstream.

**Comment by noear** [comment]
我感觉 solon 应该像 springboot 的风格去写测试代码（因为 solon 对标的是 springboot）。我改改代码再提交个 pr

**Comment by noear** [comment]
pr 已提交

**Comment by pmg1991** [comment]
Category left are : Single Db query, Multiple Db Queries, Update Db Query, Template Rendering

**Comment by noear** [comment]
还需要添加数据库查询之类的测试代码吗？

**Comment by pmg1991** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#general-test-requirements 

We have only implemented 2 Test types, 5 still left, We have to implement them using the above guide lines.

**Comment by noear** [comment]
好的。

**Comment by pmg1991** [comment]
I'll work on the rest of the categories over the weekend.

**Comment by noear** [comment]
https://solon.noear.org/start/

今天做了个 Solon Initializr (Preview)

**Comment by pmg1991** [comment]
[https://www.techempower.com/benchmarks/#section=test&runid=9072dc54-398e-4e79-b4bc-0d0a51c5aa8d&test=plaintext](url)

Solon is listed now faster than spring.

**Comment by noear** [comment]
感觉还是有点慢。理论上，应该跟 smart-servlet 差不多。

**Comment by noear** [comment]
我去看看 smart-servlet 在配置上，是不是有什么优化；）
